import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import Sidebar from '../shared/Sidebar';
import api from '../../services/api';
import useAuthStore from '../../store/authStore';
import {
  AlertTriangle, CheckCircle2, Clock, Sparkles, FileText,
  Network, CreditCard, ChevronRight, HelpCircle, Shield,
  ArrowUpRight, AlertOctagon, Loader2
} from 'lucide-react';
import toast from 'react-hot-toast';

export default function Dashboard() {
  const { company } = useAuthStore();
  const [score, setScore] = useState(null);
  const [licenses, setLicenses] = useState([]);
  const [explanation, setExplanation] = useState('');
  const [loadingExplain, setLoadingExplain] = useState(false);

  useEffect(() => {
    if (!company) return;
    api.get(`/companies/${company.companyId}/score`)
      .then(r => setScore(r.data))
      .catch(() => toast.error('Failed to load compliance score'));

    api.get(`/licenses/${company.companyId}`)
      .then(r => setLicenses(r.data))
      .catch(() => toast.error('Failed to load license timeline'));
  }, [company]);

  const getAIExplanation = async () => {
    if (!company) return;
    setLoadingExplain(true);
    try {
      const r = await api.get(`/ai/explain/${company.companyId}`);
      setExplanation(r.data.explanation);
      toast.success('Analysis generated by Claude!');
    } catch (err) {
      toast.error('Failed to generate AI explanation.');
    } finally {
      setLoadingExplain(false);
    }
  };

  const criticalLicenses = licenses.filter(l => l.daysToExpiry < 30 && l.status === 'active');
  const expiredLicenses = licenses.filter(l => l.status === 'expired' || l.daysToExpiry < 0);

  // Compliance Score display color
  const getScoreColor = (val) => {
    if (val >= 0.8) return 'text-emerald-400';
    if (val >= 0.5) return 'text-amber-400';
    return 'text-red-400';
  };

  const currentScore = score ? Math.round(score.score * 100) : 100;
  const strokeDashoffset = 251.2 - (251.2 * currentScore) / 100;

  return (
    <div className="min-h-screen gradient-bg flex">
      {/* Sidebar */}
      <Sidebar />

      {/* Main Content Pane */}
      <main className="flex-1 ml-60 p-8 min-w-0 fade-in">
        {/* Top Header */}
        <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
              Compliance Dashboard
              <div className="h-2 w-2 rounded-full bg-emerald-400 animate-ping mt-1" />
            </h1>
            <p className="text-slate-400 text-sm mt-0.5">
              Real-time Indian regulatory compliance status and AI advisor
            </p>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs text-slate-500 uppercase tracking-wider">Onboarding State</span>
            <span className="badge-active bg-emerald-500/10 border border-emerald-500/20 py-1 text-[11px] font-medium text-emerald-400">
              Live & Tracked
            </span>
          </div>
        </header>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-5 mb-8">
          {/* Circular Score ring card */}
          <div className="glass-card p-6 flex items-center justify-between relative overflow-hidden bg-slate-900/30">
            <div>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Compliance Index</p>
              <h3 className={`text-3xl font-bold mt-2 ${getScoreColor(score?.score || 1.0)}`}>
                {score ? currentScore : '--'}%
              </h3>
              <p className="text-xs text-slate-500 mt-1">Weighted metric</p>
            </div>
            
            {/* SVG Score Ring */}
            <div className="relative w-18 h-18">
              <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                <circle cx="50" cy="50" r="40" stroke="rgba(255,255,255,0.05)" strokeWidth="8" fill="transparent" />
                <circle
                  cx="50"
                  cy="50"
                  r="40"
                  stroke={score?.score >= 0.8 ? '#34d399' : score?.score >= 0.5 ? '#fbbf24' : '#f87171'}
                  strokeWidth="8"
                  fill="transparent"
                  strokeDasharray="251.2"
                  strokeDashoffset={strokeDashoffset}
                  className="transition-all duration-500"
                />
              </svg>
              <div className="absolute inset-0 flex items-center justify-center text-xs font-semibold text-white">
                CG
              </div>
            </div>
          </div>

          <div className="glass-card p-6 flex flex-col justify-between bg-slate-900/30">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Tracked Licenses</span>
              <FileText size={16} className="text-indigo-400" />
            </div>
            <div className="mt-4">
              <h3 className="text-3xl font-bold text-white">{score?.total || 0}</h3>
              <p className="text-xs text-slate-500 mt-1">Governed by state & central acts</p>
            </div>
          </div>

          <div className="glass-card p-6 flex flex-col justify-between bg-slate-900/30 border-amber-500/20">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-amber-400 uppercase tracking-wider">Expiring &lt; 30d</span>
              <Clock size={16} className="text-amber-400" />
            </div>
            <div className="mt-4">
              <h3 className="text-3xl font-bold text-amber-400">{criticalLicenses.length}</h3>
              <p className="text-xs text-slate-500 mt-1">Action required immediately</p>
            </div>
          </div>

          <div className="glass-card p-6 flex flex-col justify-between bg-slate-900/30 border-red-500/20">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-red-400 uppercase tracking-wider">Expired / Suspended</span>
              <AlertOctagon size={16} className="text-red-400" />
            </div>
            <div className="mt-4">
              <h3 className="text-3xl font-bold text-red-400">{expiredLicenses.length}</h3>
              <p className="text-xs text-slate-500 mt-1">Substantial penalty exposure</p>
            </div>
          </div>
        </div>

        {/* Quick Actions Panel */}
        <h2 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-4">Quick Operations</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-8">
          {[
            { to: '/licenses/add', icon: FileText, title: 'Add License', desc: 'Onboard a new compliance license or permit to start tracking.' },
            { to: '/graph', icon: Network, title: 'Compliance Graph', desc: 'Visualize regulatory relationships, dependencies, and bottlenecks.' },
            { to: '/ai-checklist', icon: Sparkles, title: 'Generate AI Checklist', desc: 'Consult Claude to map specific, state-focused renewal guidelines.' }
          ].map(({ to, icon: Icon, title, desc }) => (
            <Link
              key={to}
              to={to}
              className="glass-card p-5 bg-slate-900/20 hover:bg-slate-900/50 border border-white/5
                         hover:border-indigo-500/20 transition-all duration-200 group flex gap-4"
            >
              <div className="w-10 h-10 rounded-xl bg-indigo-500/10 flex items-center justify-center shrink-0
                              group-hover:bg-indigo-500/20 transition-colors">
                <Icon size={18} className="text-indigo-400" />
              </div>
              <div>
                <div className="flex items-center gap-1">
                  <h4 className="text-sm font-semibold text-white group-hover:text-indigo-300 transition-colors">
                    {title}
                  </h4>
                  <ArrowUpRight size={14} className="text-slate-500 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
                </div>
                <p className="text-xs text-slate-400 mt-1 leading-relaxed">{desc}</p>
              </div>
            </Link>
          ))}
        </div>

        {/* Critical Warnings Block */}
        {(criticalLicenses.length > 0 || expiredLicenses.length > 0) && (
          <div className="glass-card p-6 mb-8 border-red-500/10 bg-red-500/5 fade-in">
            <h3 className="text-sm font-bold text-white flex items-center gap-2 mb-4">
              <AlertTriangle size={16} className="text-amber-400 animate-bounce" />
              URGENT COMPLIANCE BREACH WARNINGS
            </h3>
            <div className="space-y-3">
              {[...expiredLicenses, ...criticalLicenses].map(l => {
                const isExpired = l.status === 'expired' || l.daysToExpiry < 0;
                return (
                  <div
                    key={l.licenseId}
                    className={`flex flex-col sm:flex-row sm:items-center justify-between p-4 rounded-xl border
                                ${isExpired
                                  ? 'bg-red-500/10 border-red-500/20 text-red-200'
                                  : 'bg-amber-500/10 border-amber-500/20 text-amber-200'
                                }`}
                  >
                    <div>
                      <span className="text-xs font-semibold tracking-wider text-slate-400 uppercase">
                        {l.licenseType?.governingAct}
                      </span>
                      <h4 className="text-sm font-bold text-white mt-0.5">
                        {l.licenseType?.name}
                      </h4>
                      <p className="text-xs text-slate-400 mt-0.5">
                        License No: {l.licenseNumber} • Regulator: {l.regulator?.name || 'State Agency'}
                      </p>
                    </div>
                    
                    <div className="mt-3 sm:mt-0 flex items-center gap-3">
                      <span className={`text-xs font-semibold px-2.5 py-1 rounded-full uppercase
                                       ${isExpired
                                         ? 'bg-red-500/20 text-red-400 border border-red-500/30'
                                         : 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                                       }`}>
                        {isExpired ? 'EXPIRED' : `${l.daysToExpiry} DAYS LEFT`}
                      </span>
                      <Link
                        to="/ai-checklist"
                        className="text-xs text-indigo-400 hover:text-indigo-300 font-semibold flex items-center gap-1"
                      >
                        Generate Guide <ChevronRight size={14} />
                      </Link>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* AI Explanation / Claude Advisory Panel */}
        <div className="glass-card p-6 bg-slate-900/30 border-white/5 relative overflow-hidden">
          {/* Backdrop Glow */}
          <div className="absolute -top-12 -right-12 w-48 h-48 bg-indigo-500/10 rounded-full blur-2xl pointer-events-none" />

          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4 pb-4 border-b border-white/5">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-indigo-500/10 flex items-center justify-center shrink-0">
                <Sparkles size={16} className="text-indigo-400" />
              </div>
              <div>
                <h3 className="text-sm font-semibold text-white">Claude AI Compliance Advisor</h3>
                <p className="text-xs text-slate-500">Real-time priority checklist based on industry type & license dates</p>
              </div>
            </div>
            
            <button
              onClick={getAIExplanation}
              disabled={loadingExplain}
              className="btn-primary py-2 px-4 text-xs h-10 flex items-center gap-2 shrink-0"
            >
              {loadingExplain ? (
                <>
                  <Loader2 size={14} className="animate-spin" />
                  Analyzing Graph...
                </>
              ) : (
                <>
                  <Sparkles size={14} />
                  Analyze My Risks
                </>
              )}
            </button>
          </div>

          <div className="fade-in">
            {explanation ? (
              <div className="bg-white/5 border border-white/8 rounded-xl p-5 text-sm text-slate-300 leading-relaxed whitespace-pre-wrap font-sans">
                {explanation}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-8 text-center px-4">
                <HelpCircle size={36} className="text-slate-600 mb-3" />
                <p className="text-sm text-slate-400 max-w-md leading-relaxed">
                  Let Claude analyze your compliance posture. We'll crawl your licenses graph and generate a prioritized strategic checklist. Click the button above to begin.
                </p>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
